title: Kristoffer Dave Tabong
logo: "profile.jpeg"
description: >
  First Description
  <br><br>
  Second Description
  <br><br>
  <a href="https://www.linkedin.com/in/kristoffer-dave-tabong-7183b2a7/">LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
